// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD52vRi542T-E1BIIiYZCdcT4xHt7bgXb4',
    appId: '1:377978954273:web:b65a493cf5c16a68e57960',
    messagingSenderId: '377978954273',
    projectId: 'badminton-accessories',
    authDomain: 'badminton-accessories.firebaseapp.com',
    storageBucket: 'badminton-accessories.firebasestorage.app',
    measurementId: 'G-77DP46M4Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQv3YE-CQQD_vr2AieEcrOfVPhLi9Im4',
    appId: '1:377978954273:android:ab91e731f9ed4abbe57960',
    messagingSenderId: '377978954273',
    projectId: 'badminton-accessories',
    storageBucket: 'badminton-accessories.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu4ABhJF4sZ6xByIhiv7VXBmMjJ34hBBc',
    appId: '1:377978954273:ios:ea79a789fb2c22e2e57960',
    messagingSenderId: '377978954273',
    projectId: 'badminton-accessories',
    storageBucket: 'badminton-accessories.firebasestorage.app',
    iosBundleId: 'com.example.badmintonAccessoriesShop',
  );

}